language: node_js
node_js:
- '6'
- '6.1'
- '5.11'
script: node_modules/karma/bin/karma start karma.conf.js --single-run
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm install
- bower install
deploy:
 provider: heroku
  app: jscontextmenu
  api_key:
   secure: ltnANHQVqXHagDXrkwRbp6EjJTjcvwxmIC+dXJQ2Jk9xHfDjqDtMuAqKYBuJeywgPvOXxi/8kmZSlfoPgvl1d3jX5SLvyPcbGyMJsB3HxWPKOgPoh1z+GEwRSQC0a+K3mAijsCpM8LupCoZxA5sF1NLw8uZ6+Rim8ceWoKaTwMZZwkg3tBQejRiLrcMG0xOiY03KOapRDBQu1fnNuaZ55fP3acsvmhddRD/dj5XuxLYRodKBAmLe55uuoI+EU2q1v5AYvJOASKDEVEcdIqJl91S5+/qY12PLr8NWPaGb9nY62rWyWBtWyPOy9Xsdt5HIKdWPTVIGnikgwd953PpoHm0/Vk4Ib+Rg8d/qwh5lBnH16ezRIOktcoWYYPY0fsRKE4ZMsPuwia6dzCZfivHUyxtf072zHDEyAWjDLvrXn5z1LcvW1IfQL1EvUt+K7lMLKPoZlNDoRL2ff/fS5QXh5xTnekBEFc15ikr9uUCgMqewZR7byxu1nJaE6b1EPE4VLgRldmUJZMYFgcjMRtfkv0OwaLWPgh1av05SzLCyX5E1pt8pBXs2wWLopmWrhPrOgVj0qf2PJee607mYr2GrYWacXtQCB6ZMkp3tMl51wU2KrRC5vHdNhuZ3ZnUyNQPuTkQFekvVG0C868EDaEQoxCJGfTwlxR7LL3nEs4kdvyw=